# Generated by Django 4.1.13 on 2024-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Your Data',
                'verbose_name_plural': 'Your Data List',
                'ordering': ['-created_at'],
            },
        ),
    ]
